version: 2.1

jobs:
  build:
    machine:
      image: android:202102-01
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
      EMULATOR_OPTS: "-no-window -no-audio -no-accel"
      PYTHONASYNCIODEBUG: 1
      CIRCLECI: 1
      LD_LIBRARY_PATH: "/opt/android/sdk/build-tools/28.0.3/lib:/opt/android/sdk/build-tools/28.0.3/lib64"
      ANDROID_HOME: /opt/android/sdk
    steps:
      - checkout
      - restore_cache:
          key: image2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: setup python venv
          command: |
            pwd
            ls
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install
            git lfs pull origin orchestrator/src/mobiletestorchestrator/resources/sdkmanager/bootstrap.zip
            python3.9 -m venv venv
            . venv/bin/activate
            pip install --upgrade -r requirements.txt
            echo 'export ANDROID_SDK_ROOT="$ANDROID_HOME"' >> $BASH_ENV
            sudo apt-get install libpulse0
      - run:
          name: build androidtestorchestrator
          command: |
            . venv/bin/activate
            pip install -e ./orchestrator
      - save_cache:
          key: image2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            - "testsupportapps/.gradle"
      - run:
          name: Run static analysis
          command: |
            . venv/bin/activate
            cd orchestrator/src
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd orchestrator/test
            mkdir -p test-reports/tmp
            /opt/android/sdk/emulator/emulator -list-avds
            CIRCLECI=1 pytest -s -v -m "not localonly" --html  test-reports/report.html --junitxml=test-reports/all-result.xml --basetemp=test-reports/tmp --cov=../src . --cov-report html:test-reports/coverage
      - run:
          name: directory
          command: |
            ls /home/circleci/code/testsupportapps/app/build/outputs/apk/androidTest/debug
            ls /home/circleci/code/testsupportapps/app/build/outputs/apk/debug
            find /home/circleci/code/orchestrator/ -name \*.apk
      - store_artifacts:
          path: orchestrator/test/test-reports/
          destination: python_app

      - store_test_results:
          path: orchestrator/test/test-reports/
workflows:
  build:
    jobs:
      - build
