version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: jrusnakli/android:api-28-py3.7
    environment:
      JVM_OPTS: -Xmx3200m
      EMULATOR_OPTS: "-no-window -no-audio -no-accel"
      PYTHONASYNCIODEBUG: 1
      ANDROID_SDK_ROOT: /opt/android/sdk
      ANDROID_AVD_HOME: /opt/android/sdk/avds
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: setup python venv
          command: |
            /usr/local/bin/python3.7 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: setup emulator
          command: |
             .circleci/setup_emulator.sh
      - run:
          name: Build support apps (debug)
          command: |
            ./testbutlerservice/gradlew androidDependencies
            ./testbutlerservice/gradlew testsupportapps:TestButlerTestApp:app:assembleDebug
            ./testbutlerservice/gradlew testsupportapps:TestButlerTestApp:app:assembleAndroidTest
      - run:
          name: Build test butler (debug)
          command: |
            cd testbutlerservice
            ./gradlew assembleDebug
            mkdir -p ../orchestrator/src/androidtestorchestrator/resources/apks
            cp app/build/outputs/apk/debug/app-debug.apk ../orchestrator/src/androidtestorchestrator/resources/apks/TestButlerLive.apk
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            - "testsupportapps/TestButlerTestApp/.gradle"
            - "testbutlerservice/.gradle"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd orchestrator/test
            pytest -s . --html  test-reports/report.html --cov=../src . --cov-report html:test-reports/coverage
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/.android/avd/MTO_emulator.avd"
      - run:
          name: directory
          command: |
            ls /home/circleci/code/orchestrator/test/../../testsupportapps/TestButlerTestApp/app/build/outputs/apk
            ls /home/circleci/code/orchestrator/test/../../testsupportapps/TestButlerTestApp/app/build/outputs/apk/debug
            find /home/circleci/code/orchestrator/ -name \*.apk
      - store_artifacts:
          path: orchestrator/test/test-reports/
          destination: python_app
